name: MacOS 编译
on:
    workflow_dispatch:

jobs:
  bundle-mac:
    timeout-minutes: 60
    name: Create a macOS bundle
    runs-on: macos-latest
    env:
      CARGO_TERM_COLOR: always
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: 1
    steps:
      - name: Install Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "18"
      - name: 设置 Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
          ref: main
          path: zed        
      - run: |
          cd zed 
          python3 replace.py
      # - name: Xcode
      #   run: |
      #     sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
      #     sudo xcodebuild -license accept
      # - name: Cmake
      #   run: brew install cmake

      - name: Set release channel to nightly
        run: |
          set -eu
          version=$(git rev-parse --short HEAD)
          echo "Publishing version: ${version} on release channel nightly"
          echo "nightly" > crates/zed/RELEASE_CHANNEL

      - name: Create macOS app bundle
        run: cd zed && script/bundle-mac

      - name: Upload Zed Nightly
        run: cd zed && script/upload-nightly macos
